# Copyright 2024 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# CI workflow running tests and linters on push and pull_request.

on: [push, pull_request]
name: Run tests
jobs:
  # Run tests and benchmarks with coverage, then check the worktree.
  test:
    name: "test: ${{matrix.os}}"
    runs-on: "${{matrix.os}}"
    continue-on-error: true
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      PYTHONDONTWRITEBYTECODE: x
    steps:
      - name: Turn off git core.autocrlf
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: "Check: go test -cover -short"
        if: always()
        run: go test -timeout=600s -v -covermode=count -coverprofile coverage.txt -bench=. -benchtime=1x -short ./...
        # Don't send code coverage if anything failed to reduce spam.
      - uses: codecov/codecov-action@v7
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: "Cleanup"
        if: always()
        run: rm -f coverage.txt codecov codecov.*
      - name: "Check: tree is clean"
        if: always()
        run: |
          # Nothing should have changed in the tree up to that point and no
          # unsuspected file was created.
          TOUCHED=$(git status --porcelain)
          if ! test -z "$TOUCHED"; then
            echo "Oops, something touched these files, please cleanup:"
            echo "$TOUCHED"
            git diff
            false
          fi

    # Run linters. This workflow can be merged with the test_all one if desired
    # to cut on runtime, at the cost of latency. I dislike waiting for results
    # so I prefer to run them in parallel.
  lint:
    name: "lint: ${{matrix.os}}"
    runs-on: "${{matrix.os}}"
    continue-on-error: true
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      PYTHONDONTWRITEBYTECODE: x
    steps:
      - name: Turn off git core.autocrlf
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - run: make verify
        if: always() && matrix.os == 'ubuntu-latest'
      - name: "Check: go generate doesn't modify files"
        if: always()
        run: |
          go generate ./...
          # Also test for untracked files.
          TOUCHED=$(git status --porcelain)
          if ! test -z "$TOUCHED"; then
            echo "go generate created these files, please fix:"
            echo "$TOUCHED"
            false
          fi
      - name: "Check: go mod tidy doesn't modify files"
        if: always()
        run: |
          go mod tidy
          TOUCHED=$(git status --porcelain)
          if ! test -z "$TOUCHED"; then
            echo "go mod tidy was not clean, please update:"
            git diff
            false
          fi

  codeql:
    name: "codeql: ${{matrix.os}}"
    runs-on: "${{matrix.os}}"
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - uses: github/codeql-action/init@v4
        with:
          languages: go
      - uses: github/codeql-action/autobuild@v4
      - uses: github/codeql-action/analyze@v4
